% 2x2 symmetric matrix inverse
syms m11 m12 m22 v1 v2
M = [m11 m12; m12 m22];
N = inv(M);
N11 = N(1,1);
N12 = N(1,2);
N22 = N(2,2);
matlabFunction(N11, N12, N22,'file','invertSymmetric2x2_autogenerated.m','vars',[m11 m12 m22]);

% 3x3 symmetric matrix inverse
syms m11 m12 m13 m22 m23 m33
M = [m11 m12 m13 ; m12 m22 m23; m13 m23 m33];
N = inv(M);
N11 = N(1,1);
N12 = N(1,2);
N13 = N(1,3);
N22 = N(2,2);
N23 = N(2,3);
N33 = N(3,3);
matlabFunction(N11,N12,N13,N22,N23,N33,'file','invertSymmetric3x3_autogenerated.m','vars',[m11 m12 m13 m22 m23 m33]);

% 4x4 symmetric matrix inverse times vector
syms m11 m12 m13 m14 m22 m23 m24 m33 m34 m44
M = [m11 m12 m13 m14 ; m12 m22 m23 m24 ; m13 m23 m33 m34; m14 m24 m34 m44];
N = inv(M);
N11 = N(1,1);
N12 = N(1,2);
N13 = N(1,3);
N14 = N(1,4);
N22 = N(2,2);
N23 = N(2,3);
N24 = N(2,4);
N33 = N(3,3);
N34 = N(3,4);
N44 = N(4,4);
matlabFunction(N11,N12,N13,N14,N22,N23,N24,N33,N34,N44,'file','invertSymmetric4x4_autogenerated.m','vars',[m11 m12 m13 m14 m22 m23 m24 m33 m34 m44]);