function [N11,N12,N22] = invertSymmetric2x2_autogenerated(m11,m12,m22)
%INVERTSYMMETRIC2X2_AUTOGENERATED
%    [N11,N12,N22] = INVERTSYMMETRIC2X2_AUTOGENERATED(M11,M12,M22)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Apr-2021 23:34:28

t2 = m11.*m22;
t3 = m12.^2;
t4 = -t3;
t5 = t2+t4;
t6 = 1.0./t5;
N11 = m22.*t6;
if nargout > 1
    N12 = -m12.*t6;
end
if nargout > 2
    N22 = m11.*t6;
end
